/*Drop Views*/
DROP VIEW REC_HASTRANS;
DROP VIEW REC_INTERVIEW;
DROP VIEW SEL;
DROP VIEW RECORDING_TOPIC;
DROP VIEW RECORDING_SPEAKER;
DROP VIEW RECORDING_INTERVIEW;

/*Drop tables*/
DROP TABLE HAS_TRANSCRIPT;
DROP TABLE TRANSCRIPT;
DROP TABLE EDITED;
DROP TABLE SUPERUSER;
DROP TABLE INTERVIEW_WITH;
DROP TABLE TOPIC_OR_CATEGORY;
DROP TABLE RECORDING;
DROP TABLE SPEAKER;


DROP EXTENSION pg_trgm CASCADE;
